apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubia
  namespace: front
  labels:
    app: kubia-f
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubia-f
  template:
    metadata:
      labels:
        app: kubia-f
    spec:
      containers:
      - name: kubia-cnt
        image: terezabisharyan/kubia
        ports:
        - containerPort: 80
